#!/usr/bin/env bash
set -eou pipefail

setup(){
  src_dir='/var/task'

  export PATH="${PATH}:${src_dir}"

  source "${src_dir}/util"

  install_dependencies
  _decrypt_secrets
}

run_docker() {
  local image="quay.io/skilbjo/iris:debian-minicon"
  local cmd="/usr/local/deploy/bin/run-job"

  udocker pull "$image"
  udocker create --name=_ "$image"
  udocker setup --execmode=F1 _
  udocker rmi -f "$image" # after creating the container, we can delete the
                          # image. after all, AWS Lambda = 512mb disk, only

  udocker run --nosysdirs \
    -v /dev -v /proc -v /etc/hosts \
    --env="_email=${email}" \
    --env="email_pw=${email_pw}" \
    --env="aws_access_key_id=${aws_access_key_id}" \
    --env="aws_secret_access_key=${aws_secret_access_key}" \
    _ /bin/bash -c '/usr/local/deploy/bin/run-job daily'

  udocker rm _            # rm cache
}

setup && \
  run_docker && \
  ping_healthchecks "$healthchecks_io_iris"
