#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app=$(basename $(dirname $dir))

cd "${dir}/.."

# this out-of-date version seems the only version of the script working atm
curl https://raw.githubusercontent.com/grycap/scar/master/lambda/udocker >/resources/udocker
