#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app=$(basename $(dirname $dir))
src_dir="/Users/skilbjo/dev/markets-etl"

cd "${dir}/../../"                   # now in ~/dev/lambdas/

cleanup(){
  if [[ -f ${app}/project.clj ]]; then rm -f ${app}/project.clj; fi
  if [[ -d ${app}/src         ]]; then rm -r ${app}/src; fi
}

copy_files(){
  cleanup

  cp "${src_dir}/project.clj"  "${app}/project.clj"
  cp -r "${src_dir}/src"       "${app}/src"
}

util_clj(){
  sed -i '' -e '1,5d;' "${app}/src/markets_etl/util.clj"

  local header='(ns markets-etl.util
  (:require [clj-time.core :as time]
            [clj-time.coerce :as coerce]
            [clojure.pprint :as pprint]
            [clojure.string :as string])
  (:import [java.util Base64]
           (java.nio ByteBuffer)
           (java.nio.charset Charset)
           [com.amazonaws.services.kms AWSKMS AWSKMSClientBuilder]
           [com.amazonaws.services.kms.model DecryptRequest]))'

  echo "$header" | cat - "${app}/src/markets_etl/util.clj" >temp && \
    mv temp "${app}/src/markets_etl/util.clj"

  local decrypt='
(defn decrypt [ciphertext]
  (let [decoder (Base64/getDecoder)
        decoded-text (.decode decoder ciphertext)
        kms-client (AWSKMSClientBuilder/defaultClient)
        decode-request (doto (DecryptRequest.)
                         (.withCiphertextBlob (ByteBuffer/wrap decoded-text)))
        decode-response (.decrypt kms-client decode-request)]
    (.toString (.decode (Charset/forName "UTF-8") (.getPlaintext decode-response)))))'

  echo "$decrypt" >>"${app}/src/markets_etl/util.clj"
}

project_clj(){
  sed -i '' -e '1,3d;' "${app}/project.clj"

  local header='(defproject markets-etl "0.1.0-SNAPSHOT"
  :uberjar-name "markets-etl.jar"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [com.amazonaws/aws-lambda-java-core "1.0.0"]
                 [com.amazonaws/aws-java-sdk-kms "1.11.98"]'

  echo "$header" | cat - "${app}/project.clj" >temp && \
    mv temp "${app}/project.clj"
}

src_files_clj(){
  sed -i '' 's/(env /(util\/decrypt /g' "${app}/src/jobs/equities.clj"
  sed -i '' 's/(env /(util\/decrypt /g' "${app}/src/jobs/currency.clj"
  sed -i '' 's/(env /(util\/decrypt /g' "${app}/src/jobs/economics.clj"
  sed -i '' 's/(env /(util\/decrypt /g' "${app}/src/jobs/interest_rates.clj"
  sed -i '' 's/(env /(util\/decrypt /g' "${app}/src/jobs/real_estate.clj"

  sed -i '' 's/(env /(util\/decrypt /g' "${app}/src/markets_etl/api.clj"
  sed -i '' 's/ env / util\/decrypt /g' "${app}/src/markets_etl/sql.clj"
}

add_aws_lambda_clj(){
  local file='(ns jobs.aws-lambda
  (:require [clojure.data.json :as json]
            [clojure.java.io :as io]
            [jobs.currency :as currency]
            [jobs.economics :as economics]
            [jobs.equities :as equities]
            [jobs.interest-rates :as interest-rates]
            [jobs.real-estate :as real-estate]
            [markets-etl.util :as util])
  (:gen-class
    :name "jobs.aws-lambda"
    :implements [com.amazonaws.services.lambda.runtime.RequestStreamHandler]))

(defn main []
  (currency/-main)
  (economics/-main)
  (equities/-main)
  (interest-rates/-main)
  (real-estate/-main))

(defn -handleRequest [_ event _ context]
  (-> event
      io/reader
      util/print-it
      (json/read :key-fn keyword)
      util/print-it))'

      echo "$file" >>src/jobs/aws_lambda.clj
}

add_lambda_wrappers(){
  util_clj
  project_clj
  src_files_clj
}


copy_files
add_lambda_wrappers
