#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"  # don't cd yet; to set app var
app="$(basename "$(dirname "$dir")")"
src_dir=''

case "$(whoami)" in
  (skilbjo)         src_dir='/Users/skilbjo/dev/markets-etl' ;;
  ('john.skilbeck') src_dir='/Users/john.skilbeck/dev/markets-etl' ;;
  ('circleci')      src_dir='/home/circleci/markets-etl' ;;
esac

cd "${dir}/../../"                   # now in ~/dev/lambdas/

cleanup(){
  if [[ -f ${app}/project.clj ]]; then rm -f ${app}/project.clj; fi
  if [[ -d ${app}/resources   ]]; then rm -r ${app}/resources; fi
  if [[ -d ${app}/src         ]]; then rm -r ${app}/src; fi
}

copy_files(){
  cleanup

  cp "${src_dir}/project.clj"  "${app}/project.clj"
  cp -r "${src_dir}/resources" "${app}/resources"
  cp -r "${src_dir}/src"       "${app}/src"
}

rm_unnecessary_files(){
  if [[ -d ${app}/src/backfill  ]]; then rm -r ${app}/src/backfill;   fi
  if [[ -d ${app}/src/benchmark ]]; then rm -rf ${app}/src/benchmark; fi # benchmark has references to test/fixtures ns, which is not copied in
}

copy_files && \
  rm_unnecessary_files
