#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )" && cd "$dir"
app="$(basename "$(dirname "$dir")")"

build() {
  deploy/build-project

  lein uberjar && \
    cp "target/uberjar/app.jar" app.jar
}

cleanup() {
  if [[ -f app.jar     ]]; then rm    app.jar; fi
  if [[ -f project.clj ]]; then rm    project.clj; fi
  if [[ -d target      ]]; then rm -r target; fi
  if [[ -d src         ]]; then rm -r src; fi
  if [[ -d resources   ]]; then rm -r resources; fi
}

update() {
  build

  if [[ $(whoami) == 'circleci' ]]; then
    # for some reason, when running uberjar on linux, the app.jar is 63mb
    # when lein uberjar is run on osx, app.jar is 45m. Unknown reason for the
    # differences
    aws s3 --profile circleci cp app.jar "s3://skilbjo/${app}.jar"

    # Note the --profile circleci flag is for skilbjo jobs inside circleci
    aws lambda update-function-code  \
      --profile circleci \
      --region us-east-1 \
      --function-name "$app" \
      --s3-bucket skilbjo \
      --s3-key "${app}.jar"
  else
    aws lambda update-function-code  \
      --profile personal \
      --region us-east-1 \
      --function-name "$app" \
      --zip-file 'fileb://app.jar'
  fi

  cleanup
}

new(){
  build

  aws lambda create-function \
    --profile personal \
    --region us-east-1 \
    --function-name "$app" \
    --zip-file 'fileb://app.jar' \
    --role arn:aws:iam::470340682667:role/lambda_with_athena \
    --handler "s3.aws-lambda" \
    --runtime java8 \
    --timeout 10 \
    --memory-size 360

  cleanup
}

update
