#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app=$(basename $(dirname $dir))

cd "${dir}/.."

build() {
  deploy/build-project

  lein uberjar && \
    cp "target/uberjar/${app}.jar" app.jar
}

cleanup() {
  if [[ -f app.jar     ]]; then rm    app.jar; fi
  if [[ -f project.clj ]]; then rm    project.clj; fi
  if [[ -d target      ]]; then rm -r target; fi
  if [[ -d src         ]]; then rm -r src; fi
  if [[ -d resources   ]]; then rm -r resources; fi
}

update() {
  build

  aws lambda update-function-code  \
    --profile personal \
    --region us-east-1 \
    --function-name "${app}" \
    --zip-file 'fileb://app.jar'

  cleanup
}

new(){
  build

  aws lambda create-function \
    --profile personal \
    --region us-east-1 \
    --function-name "${app}" \
    --zip-file 'fileb://app.jar' \
    --role arn:aws:iam::470340682667:role/lambda_with_athena \
    --handler "jobs.aws-lambda" \
    --runtime java8 \
    --timeout 10 \
    --memory-size 360

  cleanup
}

update
