#!/usr/bin/env bash
set -eou pipefail

app="us-athena-updater"

build() {
  lein uberjar && \
  cp "target/${app}.jar" app.jar
}

cleanup() {
  if [[ -f app.jar ]]; then rm app.jar; fi
  if [[ -d target ]]; then rm -r target; fi
}

update() {
  build
  aws lambda update-function-code  \
    --region us-east-1 \
    --function-name "$app" \
    --zip-file fileb://app.jar
  cleanup
}

new(){
  build
  aws lambda create-function \
    --region us-east-1 \
    --function-name "$app" \
    --zip-file file://"${app}" \
    --role arn:aws:iam::755865716437:role/lambda_with_athena \
    --handler "${app}" \
    --runtime java8 \
    --profile default \
    --timeout 10 \
    --memory-size 128
  cleanup
}

update

