version: 2.1

executors:
  machine:
    working_directory: ~/lambdas
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin
    machine:
      image: circleci/classic:latest
  clojure:
    working_directory: ~/lambdas
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin:/root/.local/bin
    docker:
      - image: circleci/clojure:lein-2.9.0    # leave this pinned; using cimg/clojure:1.10.1 fails

commands:
  start-docker:
    steps:
      - run: docker info >/dev/null 2>&1 || service docker start

jobs:
  markets-etl-and-iris:
    executor: machine
    steps:
      - checkout
      - start-docker
      - run: git clone https://github.com/skilbjo/markets-etl.git ~/markets-etl
      - run: git clone https://github.com/skilbjo/iris.git        ~/iris
      - run: mkdir -p ~/.aws; echo '[skilbjo-robot]' >~/.aws/credentials; echo "aws_access_key_id = $robot_aws_access_key_id" >>~/.aws/credentials; echo "aws_secret_access_key = $robot_aws_secret_access_key" >>~/.aws/credentials;
      - run: cd ~/markets-etl; deploy/bin/run-docker '-m s3.aws-lambda'
      - run: cd ~/iris; deploy/bin/run-docker 'daily'
  bash-etl-insights:
    executor: machine
    steps:
      - checkout
      - start-docker
      - run: git clone https://github.com/skilbjo/bash-etl.git ~/bash-etl
      - run: mkdir -p ~/.aws; echo '[skilbjo-robot]' >~/.aws/credentials; echo "aws_access_key_id = $robot_aws_access_key_id" >>~/.aws/credentials; echo "aws_secret_access_key = $robot_aws_secret_access_key" >>~/.aws/credentials;
      - run: cd ~/bash-etl; db_uri='none' deploy/bin/run-docker 'insights' # db_uri set to none is important for markets_etl_and_iris path
  markets-etl-lambda-build-and-deploy:
    executor: clojure
    steps:
      - checkout
      - run: git clone git@github.com:skilbjo/markets-etl.git ~/markets-etl
      - run: cd markets-etl; deploy/build-project
      - run: cd markets-etl; lein uberjar
      - run: if [[ $CIRCLE_BRANCH == 'master' ]]; cd markets-etl; deploy/publish-lambda; fi

workflows:
  commit:
    jobs:
      - markets-etl-lambda-build-and-deploy
      #- bash-etl-insights # uncomment to run on commits
  daily:
    jobs:
      - bash-etl-insights
    triggers:
      - schedule:
          cron: '0 3 * * *' # 8pm PST
          filters:
            branches:
              only:
                master
  friday-night:
    jobs:
      - markets-etl-and-iris
    triggers:
      - schedule:
          cron: '0 3 * * 6' # 7,8,9pm PST # 0 2,3,4 * * 2-6  # Just leave on Fri so not to run up aws costs
          filters:
            branches:
              only:
                master
