#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app=$(basename $(dirname $dir))

cd "${dir}/.."

test_code() {
  # for S3 trigger
    #--payload 'file://test/s3_event' \

  # for SNS trigger
    #--payload 'file://test/sns_event' \
  aws lambda invoke \
    --profile personal \
    --invocation-type Event \
    --region us-east-1 \
    --function-name "${app}_update-athena" \
    --payload 'file://test/sns_event' \
    test/response
}

#test_code && cat test/response

integration_test(){
  touch file.csv
  aws --profile personal s3 cp file.csv s3://skilbjo-data/datalake/markets-etl/test/file.csv
  rm file.csv
}

integration_test
