#!/usr/bin/env bash
set -eou pipefail

setup(){
  src_dir='/var/task'

  export PATH="${PATH}:${src_dir}"

  source "${src_dir}/util"

  install_dependencies
  #_decrypt_secrets
}

setup

uname -a
set +x
udocker install

# Note, Alpine images don't seem to be working
# try https://github.com/bitnami/minideb as an alternative
#udocker pull busybox # quay.io/skilbjo/iris:x86
udocker pull grycap/cowsay # quay.io/skilbjo/iris:x86

#udocker create --name=iris busybox # quay.io/skilbjo/iris:x86
udocker create --name=iris grycap/cowsay # quay.io/skilbjo/iris:x86

udocker setup --execmode=F1 iris

udocker run -v /tmp -v /dev -v /proc -v /etc/hosts --nosysdirs \
  iris cat /etc/os-release
