#!/usr/bin/env bash
set -eou pipefail

setup(){
  src_dir='/var/task'

  export PATH="${PATH}:${src_dir}"

  source "${src_dir}/util"

  install_dependencies
  #_decrypt_secrets
}

setup

set -x
udocker install

udocker pull busybox # quay.io/skilbjo/iris:x86
udocker create --name=iris busybox # quay.io/skilbjo/iris:x86
udocker setup --execmode=F1 iris

udocker run -v /dev -v /proc -v /etc/hosts --nosysdirs \
  iris ls /etc
