#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app=$(basename $(dirname $dir))

cd "${dir}/.."

add_awscli(){
  # https://alestic.com/2016/11/aws-lambda-awscli/
  mkdir tmp
  virtualenv="virtual-env"
  zipfile="$(pwd)/app.zip"
  (
    cd tmp; virtualenv virtual-env
    set +u
    source virtual-env/bin/activate
    set -u
    pip install awscli # add any addtl libraries here; or requirements.txt
    rsync -va "virtual-env/bin/aws" aws
    perl -pi -e '$_ = "#!/usr/bin/python\n" if $. == 1' aws
    zip -r9 "$zipfile" aws
    cd "virtual-env/lib/python2.7/site-packages"; zip -r9 "$zipfile" .
  )
}

build() {
  add_awscli

  cd src;
  zip -r9 ../app.zip . && \
    cd ../ && \
  chmod 744 app.zip
}

add_npm(){
  zipfile="$(pwd)/app.zip"

  (
    cd tmp
    if [[ ! -d node_modules ]]; then
      npm install jsonlint # add any addtl libaries here; or package.json
    fi
    zip -r9 "$zipfile" node_modules
  )
}

add_bin(){
  # remember, must be built for AWS AMI (not macOS)

  ## jq
  zipfile="$(pwd)/app.zip"
  (
    cd tmp
    if [[ ! -f jq ]]; then
      curl -L \
        https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 \
        -o jq
      chmod +x jq
      zip -r9 "$zipfile" jq
    fi
  )

  ## git
  (
    cd tmp
    cp ../resources/git.tar .
    zip -r9 "$zipfile" jq
  )
}

dev(){
  if [[ ! -f app.zip ]]; then
    add_awscli
    #add_npm
    add_bin
  fi

  cd src && \
    zip -r9 ../app.zip . && \
    cd ../ && \
  chmod 744 app.zip

  aws lambda update-function-code  \
    --profile personal \
    --region us-east-1 \
    --function-name "${app}" \
    --zip-file 'fileb://app.zip'
}

cleanup() {
  if [[ -d tmp     ]]; then rm -rf tmp; fi
  if [[ -f app.zip ]]; then rm app.zip; fi
}

update() {
  build

  aws lambda update-function-code  \
    --profile personal \
    --region us-east-1 \
    --function-name "${app}" \
    --zip-file 'fileb://app.zip'

  cleanup
}

new(){
  build

  aws lambda create-function \
    --profile personal \
    --region us-east-1 \
    --function-name "${app}" \
    --zip-file 'fileb://app.zip' \
    --role arn:aws:iam::470340682667:role/lambda_with_s3 \
    --handler 'entrypoint.lambda_handler' \
    --runtime 'python3.6' \
    --timeout 60 \
    --memory-size 128

  cleanup
}

dev
