#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app=$(basename $(dirname $dir))

cd "${dir}/.."

test_code() {
  aws lambda invoke \
    --profile default \
    --invocation-type Event \
    --region us-east-1 \
    --function-name "${app}" \
    --payload 'file://test/cloudwatch_events_rules' \
    test/response
}

test_code && cat test/response
