#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app_name=$(basename $(dirname $dir))

docker run --rm -it \
  --name="$(echo $app_name)" \
  -e _email="$(echo $email)" \
  -e email_pw="$(echo $email_pw)" \
  -e aws_access_key_id="$(echo $aws_access_key_id)" \
  -e aws_secret_access_key="$(echo $aws_secret_access_key)" \
  -e healthchecks_io_api_key="$(echo $healthchecks_io_api_key)" \
  quay.io/skilbjo/iris:minicon bash
