#!/usr/bin/env bash
set -eou pipefail

setup(){
  src_dir='/var/task'

  export PATH="${PATH}:${src_dir}"

  source "${src_dir}/util"

  install_dependencies
  #_decrypt_secrets
}

run_docker() {
  local image="$1"
  local cmd="$2"

  udocker install

  udocker pull "$image"
  udocker create --name=_ "$image"
  udocker setup --execmode=F1 _

  udocker run --nosysdirs _ $cmd
}

setup && \
  run_docker quay.io/skilbjo/iris:x86 /usr/local/deploy/bin/run-job
