#!/usr/bin/env bash
set -eou pipefail

aws_works(){
  echo 'aws works'
  #aws s3 cp s3://skilbjo-data/datalake/markets-etl/currency/s3uploaddate=2018-02-03/file.csv /tmp/
  #cat /tmp/file.csv
}

fn(){
  echo 'Im in a fn'
}

cpu_info(){
  env_vars=$(env)
  user=$(whoami)
  kernel=$(uname -a)
  distro=$(cat /etc/*-release)
  cores=$(getconf _NPROCESSORS_ONLN 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || echo 1)

  echo "env vars are: $env_vars"
  echo "user is $user"
  echo "kernel is $kernel"
  echo "distro is $distro"
  echo "number of cores is: $cores"

  echo '/etc/passwd is:'
  cat /etc/passwd
}
