#!/usr/bin/env bash
set -eou pipefail

setup(){
  src_dir='/var/task'

  export PATH="${PATH}:${src_dir}"

  source "${src_dir}/util"
  source "${src_dir}/misc"
  source "${src_dir}/athena"

  install_dependencies
}

setup

aws s3 ls

echo 'gonna try jq'
echo '{"hi": 1}' | jq .

echo 'gonna try jsonlint'
echo '{"hi": 1}' | jsonlint

echo 'curl'
curl https://skilbjo.duckdns.org/api/currency/latest | jsonlint

query "select 1+1 as hello_athena"

which git

#echo 'curl with -k'
#curl -k https://skilbjo-aws.duckdns.org/api/currency/latest | jq .
