#!/usr/bin/env bash
set -eou pipefail

dir='/tmp/bin'
src_dir='/var/task'

export PATH="${PATH}:/var/task"

setup(){
  source "${src_dir}/cpu-info"
}

setup

aws s3 cp s3://skilbjo-data/datalake/markets-etl/currency/s3uploaddate=2018-02-03/file.csv /tmp/

cat /tmp/file.csv
