#!/usr/bin/env bash
set -eou pipefail

setup(){
  src_dir='/var/task'

  export PATH="${PATH}:${src_dir}"

  source "${src_dir}/util"
  source "${src_dir}/misc"
  source "${src_dir}/athena"

  install_dependencies
  add_ssh_key
}

setup

aws s3 ls

slack "bash-it: i ran"

echo 'calling decrypt fn'
add_ssh_key

set +e
echo 'is there nc?'
which nc
