#!/usr/bin/env bash
set -eou pipefail

sns_event='{
    "Records": [
        {
            "EventVersion": "1.0",
            "EventSubscriptionArn": "arn:aws:sns:us-east-1:755865716437:US-Marketplace_bank-transaction-publisher:3706185f-8590-4422-a7f4-42a4063a79af",
            "EventSource": "aws:sns",
            "Sns": {
                "SignatureVersion": "1",
                "Timestamp": "2017-12-05T23:01:53.634Z",
                "Signature": "E5VlkbH3xL4YmhubxlIxmIZl78PoCKWXPfevCC12qp5h/LCToUKHagg31zlxAd87oPEl5egR18evOdtdg8aqL5cgRMktBBXfv4OCBk9qg37qaQf4CWKgUJL1gCEbXKeXiTY7MzlhfFgauu4I4opK7RPYSD0UpgrHZoaUW3jioan7wM1fZ3975d993OA0A9CrmckAifkRl94esDZC9rkkinl0zkiQJUkSIwNLprRBxOOH64FuN2yIs7+1o10DElrFPmZhMBrA+2VV3pYiNyp3b5VDYtHPF43ask1lG1Ogsb+0A3JszPPgFlZyBiHsyXSWs8bDJcXfdmAzGvpSy3hVEQ==",
                "SigningCertUrl": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-433026a4050d206028891664da859041.pem",
                "MessageId": "581d347d-5460-57ad-a14e-66dc73c1b21d",
                "Message": {
                    "Records": [
                        {
                            "eventVersion": "2.0",
                            "eventSource": "aws:s3",
                            "awsRegion": "us-east-1",
                            "eventTime": "2017-12-05T23:01:53.306Z",
                            "eventName": "ObjectCreated:Put",
                            "userIdentity": {
                                "principalId": "AWS:AIDAI3IRQMWCYVU7P5UUG"
                            },
                            "requestParameters": {
                                "sourceIPAddress": "50.232.12.18"
                            },
                            "responseElements": {
                                "x-amz-request-id": "A18B08A68BD810F5",
                                "x-amz-id-2": "IfJHxDGBG2CBEzFoFjAc1cs50HoITnie2m8fijnTIxPFpskGzSvYV1SSGx8USuT6n3qo/zAA4rc="
                            },
                            "s3": {
                                "s3SchemaVersion": "1.0",
                                "configurationId": "50584385-f2ff-4fc6-86fc-0196ec24954c",
                                "bucket": {
                                    "name": "skilbjo-data",
                                    "ownerIdentity": {
                                        "principalId": "A128U96DN62YT0"
                                    },
                                    "arn": "arn:aws:s3:::skilbjo-data"
                                },
                                "object": {
                                    "key": "some-file-here",
                                    "size": 879974,
                                    "eTag": "317721a717fb08f94f2567f216f652c3",
                                    "sequencer": "005A27255F9488BEBA"
                                }
                            }
                        }
                    ]
                },
                "MessageAttributes": {},
                "Type": "Notification",
                "UnsubscribeUrl": "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:755865716437:US-Marketplace_bank-transaction-publisher:3706185f-8590-4422-a7f4-42a4063a79af",
                "TopicArn": "arn:aws:sns:us-east-1755865716437:US-Marketplace_bank-transaction-publisher",
                "Subject": "Amazon S3 Notification"
            }
        }
    ]
}'

bucket="$(echo "$sns_event" | jq -r '.Records[].Sns.Message.Records[].s3.bucket.name')"
file="$(echo "$sns_event" | jq -r '.Records[].Sns.Message.Records[].s3.object.key')"

#echo "bucket is: $bucket"
#echo "file is: $file"

s3_portion='{
    "Records": [
        {
            "eventVersion": "2.0",
            "eventSource": "aws:s3",
            "awsRegion": "us-east-1",
            "eventTime": "2018-07-24T23:53:40.070Z",
            "eventName": "ObjectCreated:Put",
            "userIdentity": {
                "principalId": "AWS:AROAJ7XRZKOAKH2VUSBFS:i-00c6982788a989740"
            },
            "requestParameters": {
                "sourceIPAddress": "54.196.170.38"
            },
            "responseElements": {
                "x-amz-request-id": "05B80A84CAAD40FB",
                "x-amz-id-2": "hI3/b3G5aXwUUv/T8BdLQjQf8jsfwPjZxgo8mqZlWdnWW9SFnzgUgxXqG/U2iakEvh5lWfLtHAw="
            },
            "s3": {
                "s3SchemaVersion": "1.0",
                "configurationId": "data-team-s3-folder-updated",
                "bucket": {
                    "name": "skilbjo-data",
                    "ownerIdentity": {
                        "principalId": "AF6D16DSVTVEJ"
                    },
                    "arn": "arn:aws:s3:::skilbjo-data"
                },
                "object": {
                    "key": "data/stripe/events.csv.gz",
                    "size": 6025472,
                    "eTag": "dc2cf0e7b82f52c0379c2802688f34d5",
                    "sequencer": "005B57BC03B14B4732"
                }
            }
        }
    ]
}'

file_jq='.Records[].s3.object.key'

file_json="$(echo "$s3_portion" | jq -r "$file_jq")"

file=$(basename $file_json .csv.gz)

echo "$file"
