#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app=$(basename $(dirname $dir))

cd "${dir}/.."

# this out-of-date version seems the only version of the script working atm
curl https://raw.githubusercontent.com/grycap/scar/master/lambda/udocker >resources/udocker

# up to date
curl https://raw.githubusercontent.com/grycap/scar/master/src/providers/aws/cloud/lambda/udocker/udocker.py >resources/udocker

# saved version
https://raw.githubusercontent.com/skilbjo/lambdas/master/iris/resources/udocker >resources/udocker
