#!/usr/bin/env bash
set -eou pipefail

sns_event="$1"

setup(){
  src_dir='/var/task'

  export PATH="${PATH}:${src_dir}"

  source "${src_dir}/util"
  source "${src_dir}/athena"

  install_dependencies
  _decrypt_secrets
}

refresh_partitions(){
  schema="$1"
  table="$2"

  query "msck repair table ${schema}.${table};"
  echo "msck repair table ran for ${schema}.${table}"
}

setup && \
  refresh_partitions "logs" "s3"
